// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDmMlB5MO_zPAgRRewwv3SBM7ZU8UsxNrs',
    appId: '1:678290258619:web:de48dc97d12400a426c79e',
    messagingSenderId: '678290258619',
    projectId: 'kampuskart-3987a',
    authDomain: 'kampuskart-3987a.firebaseapp.com',
    storageBucket: 'kampuskart-3987a.firebasestorage.app',
    measurementId: 'G-15GJ0FCPCQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDR1DN59HxxNEUuhtiPpdw4WNCMShJQK_4',
    appId: '1:678290258619:android:cca204686ceba38e26c79e',
    messagingSenderId: '678290258619',
    projectId: 'kampuskart-3987a',
    storageBucket: 'kampuskart-3987a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCMBOwNg9j70qHLCcSXh1wWdJFVcMAEsvY',
    appId: '1:678290258619:ios:8cbd192e21c4fb4326c79e',
    messagingSenderId: '678290258619',
    projectId: 'kampuskart-3987a',
    storageBucket: 'kampuskart-3987a.firebasestorage.app',
    iosBundleId: 'com.example.kampusKart',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCMBOwNg9j70qHLCcSXh1wWdJFVcMAEsvY',
    appId: '1:678290258619:ios:8cbd192e21c4fb4326c79e',
    messagingSenderId: '678290258619',
    projectId: 'kampuskart-3987a',
    storageBucket: 'kampuskart-3987a.firebasestorage.app',
    iosBundleId: 'com.example.kampusKart',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDmMlB5MO_zPAgRRewwv3SBM7ZU8UsxNrs',
    appId: '1:678290258619:web:f805ea2c98363a8926c79e',
    messagingSenderId: '678290258619',
    projectId: 'kampuskart-3987a',
    authDomain: 'kampuskart-3987a.firebaseapp.com',
    storageBucket: 'kampuskart-3987a.firebasestorage.app',
    measurementId: 'G-R25JP65JNJ',
  );
}
